Express example app - fixes
MentorMate/node-project-cli pull request #307
Opened 2023-12-19 08:38 UTC by Yavorss

2023-12-20 19:48 UTC, IvayloGrahlyov requested changes
While on express could you please also update the `nodemon` version to `v3.0.2` to resolve a CVE
Running the e2e tests results in:
```
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

2023-12-20 19:48 UTC, IvayloGrahlyov commented on src/extensions/setup-auth0.js
> +          AUTH0_CLIENT_ID: 'https://mock.auth0.com/api/v2/',
This needs to be the `AUTH0_ISSUER_URL`

2023-12-20 20:34 UTC, Yavorss commented on src/extensions/setup-auth0.js
> +          AUTH0_CLIENT_ID: 'https://mock.auth0.com/api/v2/',
🤦

2023-12-21 11:48 UTC, PetarParushevMM approved these changes

2023-12-21 17:30 UTC, IvayloGrahlyov approved these changes

2023-12-21 18:10 UTC, PetarParushevMM approved these changes

2023-12-21 18:10 UTC, IvayloGrahlyov approved these changes

2023-12-21 18:13 UTC, merged